# Generated by Django 5.2.12 on 2026-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_jpl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdetail',
            name='dec',
            field=models.FloatField(blank=True, help_text='Declination at the ephemeris time (degrees)', null=True, verbose_name='Declination'),
        ),
        migrations.AddField(
            model_name='scoutdetail',
            name='ra',
            field=models.FloatField(blank=True, help_text='Right ascension at the ephemeris time (degrees)', null=True, verbose_name='Right Ascension'),
        ),
        migrations.AddField(
            model_name='scoutdetail',
            name='rate',
            field=models.FloatField(blank=True, help_text='Plane-of-sky motion rate (arcsec/min)', null=True, verbose_name='Sky motion'),
        ),
        migrations.AddField(
            model_name='scoutdetail',
            name='t_ephem',
            field=models.DateTimeField(blank=True, help_text='Time the ephemeris quantities (ra, dec, vmag, rate) are valid for', null=True, verbose_name='Ephemeris time'),
        ),
        migrations.AddField(
            model_name='scoutdetail',
            name='vmag',
            field=models.FloatField(blank=True, help_text='Predicted V magnitude', null=True, verbose_name='V Magnitude'),
        ),
    ]
