# Generated by Django 5.2.12 on 2026-06-05 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_jpl', '0002_scoutdetail_dec_scoutdetail_ra_scoutdetail_rate_and_more'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdetail',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the object is still on the Scout list (False once it has left, e.g. designated, removed, or impacted)'),
        ),
        migrations.CreateModel(
            name='ScoutDetailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_obs', models.IntegerField(blank=True, help_text='Number of observations', null=True)),
                ('neo_score', models.IntegerField(blank=True, help_text='NEO digest score (0..100)', null=True, verbose_name='NEO Score')),
                ('neo1km_score', models.IntegerField(blank=True, help_text='NEO >1km digest score (0..100)', null=True, verbose_name='NEO >1km Score')),
                ('pha_score', models.IntegerField(blank=True, help_text='PHA digest score (0..100)', null=True, verbose_name='PHA Score')),
                ('ieo_score', models.IntegerField(blank=True, help_text='IEO digest score (0..100)', null=True, verbose_name='IEO Score')),
                ('geocentric_score', models.IntegerField(blank=True, help_text='Geocentric digest score (0..100)', null=True, verbose_name='Geocentric Score')),
                ('impact_rating', models.IntegerField(blank=True, choices=[(0, 'Negligible'), (1, 'Small'), (2, 'Modest'), (3, 'Moderate'), (4, 'Elevated')], help_text='Impact rating (0=negligible, 1=small, 2=modest, 3=moderate, 4=elevated)', null=True)),
                ('ca_dist', models.FloatField(blank=True, help_text='Close approach distance (lunar distances)', null=True)),
                ('arc', models.FloatField(blank=True, help_text='Arc length (days)', null=True)),
                ('rms', models.FloatField(blank=True, help_text='RMS of the residuals to the orbit fit (arcsec)', null=True)),
                ('uncertainty', models.FloatField(blank=True, help_text='1-sigma plane-of-sky positional uncertainty (arcmin)', null=True, verbose_name='Uncertainty')),
                ('uncertainty_p1', models.FloatField(blank=True, help_text='1-sigma plane-of-sky positional uncertainty at +1 day (arcmin)', null=True, verbose_name='Uncertainty at +1 day')),
                ('vmag', models.FloatField(blank=True, help_text='Predicted V magnitude', null=True, verbose_name='V Magnitude')),
                ('rate', models.FloatField(blank=True, help_text='Plane-of-sky motion rate (arcsec/min)', null=True, verbose_name='Sky motion')),
                ('ra', models.FloatField(blank=True, help_text='Right ascension at the ephemeris time (degrees)', null=True, verbose_name='Right Ascension')),
                ('dec', models.FloatField(blank=True, help_text='Declination at the ephemeris time (degrees)', null=True, verbose_name='Declination')),
                ('t_ephem', models.DateTimeField(blank=True, help_text='Time the ephemeris quantities (ra, dec, vmag, rate) are valid for', null=True, verbose_name='Ephemeris time')),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time the data was updated from Scout', null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_detail_history', to='tom_targets.basetarget')),
            ],
            options={
                'verbose_name': 'Scout Detail History',
                'ordering': ['target', 'last_run'],
                'unique_together': {('target', 'last_run')},
            },
        ),
    ]
