# Generated by Django 5.2.14 on 2026-06-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_jpl', '0003_scoutdetail_active_scoutdetailhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutdetailhistory',
            options={'ordering': ['target', 'last_run'], 'verbose_name': 'Scout Detail History', 'verbose_name_plural': 'Scout Detail Histories'},
        ),
    ]
