# Generated by Django 5.2.16 on 2026-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_jpl', '0004_alter_scoutdetailhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdetail',
            name='merged_into',
            field=models.CharField(blank=True, help_text='Name or alias of the object this submission became, when its identity lives on another Target: the MPC identified two submissions as the same body, or the designation was already held (e.g. ingested independently from MPC/JPL). The designation itself is never copied here -- names live only on Target/TargetName; resolve with resolve_merged_into().', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scoutdetail',
            name='mpc_reference',
            field=models.CharField(blank=True, help_text="Publication announcing the outcome recorded in mpc_status (e.g. 'MPEC 2026-Q53'), as given by the MPC Previous NEOCP Objects page.", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scoutdetail',
            name='mpc_status',
            field=models.CharField(blank=True, choices=[('designated', 'received an IAU designation'), ('lost', 'was not confirmed'), ('dne', 'does not exist'), ('na', 'not a minor planet (matched to a known artificial satellite)'), ('ns', 'suspected artificial (geocentric orbit, no match to a known satellite)')], help_text="Why the object left the NEOCP, per the MPC's Previous NEOCP Objects page. Null until that outcome has been established; once set, the object is settled and is no longer looked up against the MPC.", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='scoutdetail',
            name='mpc_status_checked',
            field=models.DateTimeField(blank=True, help_text='UTC time when the MPC was last consulted about this object. Recorded even when no outcome was found, so a candidate the MPC has no row for yet is visibly pending rather than silently stale.', null=True),
        ),
    ]
